language: java

install: true
jdk:  
 - oraclejdk8
 
 addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false

branches:
  only:
  - master
notifications:
  email:
  - sharomov.v@gmail.com
  on_success: always
  on_failure: never
